# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: my_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10my_service.proto\x12\nmy_service\";\n\x15\x41uthenticationRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\")\n\x16\x41uthenticationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"!\n\x0e\x43ommandRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"!\n\x0f\x43ommandResponse\x12\x0e\n\x06output\x18\x01 \x01(\t2p\n\x15\x41uthenticationService\x12W\n\x0c\x41uthenticate\x12!.my_service.AuthenticationRequest\x1a\".my_service.AuthenticationResponse\"\x00\x32Y\n\x0e\x43ommandService\x12G\n\nRunCommand\x12\x1a.my_service.CommandRequest\x1a\x1b.my_service.CommandResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'my_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AUTHENTICATIONREQUEST._serialized_start=32
  _AUTHENTICATIONREQUEST._serialized_end=91
  _AUTHENTICATIONRESPONSE._serialized_start=93
  _AUTHENTICATIONRESPONSE._serialized_end=134
  _COMMANDREQUEST._serialized_start=136
  _COMMANDREQUEST._serialized_end=169
  _COMMANDRESPONSE._serialized_start=171
  _COMMANDRESPONSE._serialized_end=204
  _AUTHENTICATIONSERVICE._serialized_start=206
  _AUTHENTICATIONSERVICE._serialized_end=318
  _COMMANDSERVICE._serialized_start=320
  _COMMANDSERVICE._serialized_end=409
# @@protoc_insertion_point(module_scope)
